### ISSUE TITLE
Cambios finales

### ISSUE THREAD

**Issue by javijuventus** [alvarsnow/tienda#10]
Rellenar hrefs  de alguna  imagen de algun portatil para que vayan a producto.html

Añadir imagenes validacion de w3c en footer o  dónde se quiera. (OPCIONAL)
validador css:
https://jigsaw.w3.org/css-validator/#validate_by_upload
validar htmls:
https://validator.w3.org/#validate_by_upload

**Comment by javijuventus** [comment]
El footer no tiene mucha usabilidad si se os ocurre como mejorarlo , estaria bien.

**Comment by AlvarSML** [comment]
Done
